window.CALL_TICKET_BOT_MODEL = {
  "version": 1,
  "trainedAt": "2026-04-23T04:04:10.637Z",
  "totalDocs": 70,
  "vocabulary": [
    "2026-05-12",
    "22",
    "24",
    "28",
    "31",
    "35",
    "aaj",
    "age",
    "ahead",
    "amount",
    "anika",
    "are",
    "before",
    "bengaluru",
    "bhejo",
    "book",
    "booking",
    "bot",
    "by",
    "call",
    "can",
    "cancel",
    "car",
    "chahiye",
    "chair",
    "change",
    "chennai",
    "clear",
    "confirm",
    "confirmed",
    "delhi",
    "departure",
    "details",
    "dobara",
    "evening",
    "everything",
    "final",
    "from",
    "galat",
    "general",
    "go",
    "good",
    "haan",
    "hear",
    "hello",
    "hi",
    "hyderabad",
    "jaipur",
    "journey",
    "kal",
    "karni",
    "karo",
    "kolkata",
    "later",
    "link",
    "liye",
    "local",
    "lower",
    "message",
    "mobile",
    "morning",
    "mujhe",
    "mumbai",
    "namaskar",
    "namaste",
    "name",
    "neha",
    "new",
    "now",
    "ok",
    "on",
    "ordinary",
    "over",
    "passenger",
    "pay",
    "payment",
    "phone",
    "proceed",
    "pune",
    "rahul",
    "raj",
    "reservation",
    "reserve",
    "reserved",
    "reset",
    "restart",
    "seat",
    "send",
    "shuru",
    "sita",
    "sleeper",
    "sms",
    "start",
    "suno",
    "there",
    "ticket",
    "today",
    "tomorrow",
    "train",
    "travel",
    "umar",
    "unreserved",
    "want",
    "will",
    "window",
    "yes",
    "you"
  ],
  "labels": {
    "book_ticket": {
      "docs": 10,
      "totalTokens": 43,
      "tokenCounts": {
        "book": 5,
        "ticket": 8,
        "from": 3,
        "delhi": 3,
        "mumbai": 3,
        "tomorrow": 2,
        "want": 1,
        "reserve": 2,
        "train": 1,
        "chahiye": 2,
        "mujhe": 1,
        "karni": 1,
        "chennai": 1,
        "bengaluru": 1,
        "journey": 1,
        "pune": 1,
        "hyderabad": 1,
        "seat": 1,
        "jaipur": 1,
        "kolkata": 1,
        "karo": 1,
        "kal": 1,
        "liye": 1
      },
      "reply": "Sure, I can book that. Please tell me the source, destination, travel date, passenger name, and age."
    },
    "journey_type": {
      "docs": 10,
      "totalTokens": 25,
      "tokenCounts": {
        "reserved": 3,
        "journey": 2,
        "unreserved": 2,
        "local": 3,
        "train": 2,
        "general": 1,
        "ticket": 3,
        "want": 1,
        "book": 1,
        "sleeper": 1,
        "reservation": 1,
        "chair": 1,
        "car": 1,
        "ordinary": 1,
        "confirmed": 1,
        "seat": 1
      },
      "reply": "Thanks. I will note whether the journey is reserved or unreserved."
    },
    "provide_details": {
      "docs": 10,
      "totalTokens": 48,
      "tokenCounts": {
        "22": 1,
        "24": 1,
        "28": 2,
        "31": 1,
        "35": 1,
        "from": 3,
        "delhi": 2,
        "mumbai": 2,
        "tomorrow": 1,
        "rahul": 2,
        "age": 5,
        "kal": 1,
        "umar": 1,
        "name": 2,
        "anika": 1,
        "passenger": 1,
        "sita": 1,
        "will": 1,
        "travel": 1,
        "chennai": 2,
        "bengaluru": 2,
        "today": 1,
        "window": 1,
        "seat": 2,
        "raj": 1,
        "kolkata": 1,
        "pune": 1,
        "on": 1,
        "2026-05-12": 1,
        "hyderabad": 1,
        "jaipur": 1,
        "neha": 1,
        "aaj": 1,
        "lower": 1
      },
      "reply": "Thanks. I am filling those details now."
    },
    "payment": {
      "docs": 10,
      "totalTokens": 30,
      "tokenCounts": {
        "send": 3,
        "payment": 6,
        "link": 4,
        "sms": 3,
        "bhejo": 1,
        "pay": 3,
        "by": 1,
        "phone": 1,
        "will": 1,
        "later": 1,
        "before": 1,
        "departure": 1,
        "message": 1,
        "mobile": 1,
        "ticket": 1,
        "amount": 1
      },
      "reply": "I will send the payment link by SMS after confirmation."
    },
    "confirm_booking": {
      "docs": 10,
      "totalTokens": 21,
      "tokenCounts": {
        "confirm": 3,
        "yes": 2,
        "book": 4,
        "go": 1,
        "ahead": 1,
        "ticket": 2,
        "karo": 3,
        "haan": 1,
        "ok": 1,
        "now": 1,
        "proceed": 1,
        "final": 1
      },
      "reply": "I will confirm the booking now."
    },
    "reset_booking": {
      "docs": 10,
      "totalTokens": 21,
      "tokenCounts": {
        "start": 1,
        "over": 1,
        "reset": 1,
        "cancel": 2,
        "booking": 2,
        "clear": 1,
        "details": 2,
        "dobara": 1,
        "shuru": 1,
        "karo": 2,
        "change": 1,
        "everything": 1,
        "new": 1,
        "ticket": 1,
        "restart": 1,
        "call": 1,
        "galat": 1
      },
      "reply": "No problem. I have cleared the booking details."
    },
    "greeting": {
      "docs": 10,
      "totalTokens": 17,
      "tokenCounts": {
        "hello": 2,
        "hi": 1,
        "namaste": 1,
        "good": 2,
        "morning": 1,
        "evening": 1,
        "are": 1,
        "you": 2,
        "there": 1,
        "can": 1,
        "hear": 1,
        "suno": 1,
        "bot": 1,
        "namaskar": 1
      },
      "reply": "Hello. I can help you book a ticket by call."
    }
  }
};
